server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:root}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:project-tracker}?authSource=admin